### ISSUE TITLE
Incomplete hyperlink area in ***InTheNews***

### ISSUE THREAD

**Issue by CandyZQ** [CSbyUs/csbyus-on-rails#22]
Right now cards in ***InTheNews*** only have hyperlink on **LEARN MORE** button, but actually the entire cards are clickable. It can be nice if we also set the upper section of the cards a hyperlink directed to the same website, or even hide **LEARN MORE** button if possible.

**Comment by tannerljohnson** [comment]
great catch @CandyZQ! might also be a good idea to create a clickable CardActionArea for cards in every part of the site (e.g., curriculahub)
