### ISSUE TITLE
fix `bundle install` issue

### ISSUE THREAD

**Issue by tannerljohnson** [CSbyUs/csbyus-on-rails#98]
should be able to push without changes

**Comment by tannerljohnson** [comment]
https://github.com/CSbyUs/csbyus-on-rails/commit/e6dfe261e8bc20478bbce485628f85f42c1289d0

**Comment by eparadise** [comment]
Is there anything I have to do for the new Gemfile? When I ran bundle install I got this error: 

<img width="667" alt="Screen Shot 2020-06-09 at 1 09 39 PM" src="https://user-images.githubusercontent.com/43389857/84178515-8db96880-aa52-11ea-89a4-6fcf5d37787e.png">

**Comment by tannerljohnson** [comment]
hmmm which branch are you on @eparadise ? are you up to date with `master` (pulled from master or rebased your branch ontop of master)?

**Comment by eparadise** [comment]
Yes I'm up to date with master. I'm on an eslint branch that I made, but I rebased with master and I just tried rails s and bundle install in master and got the same errors.

**Comment by tannerljohnson** [comment]
> Yes I'm up to date with master. I'm on an eslint branch that I made, but I rebased with master and I just tried rails s and bundle install in master and got the same errors.

what does your gemfile look like? can you push your branch and point me to it so i can see?
can you also try `git checkout master && git pull origin master && bundle install` ?
